In [1]:
import numpy as np

In [2]:
np.random.randint(0,101,3)

array([88, 22, 85])

In [3]:
def wuerfel(anzahl_gruppen):
    ready = False
    while not ready:
        trial = np.random.randint(0,101,anzahl_gruppen)
        print(trial)
        if len(set(trial)) == len(trial):
            ready = True
    print("Finales Ergebnis:", trial)

In [16]:
wuerfel(2)

[31 92]
Finales Ergebnis: [31 92]


In [28]:
arr=np.array([5,10,11,1,8,4,14])
np.random.shuffle(arr)
print(arr)

[14  4  1  5  8 11 10]


In [31]:
print(np.arange(7)+1+(13-6))
print(arr)

[ 8  9 10 11 12 13 14]
[14  4  1  5  8 11 10]


In [15]:
def reihenfolge_erfuellt_kriterien(reihenfolge):
    tests = []
    for index, fragen_index in enumerate(reihenfolge):
        test = True
        gruppe = index + 1
        print(gruppe, fragen_index)
        test = test and not (gruppe == fragen_index) # Gruppe soll sich nicht selbst fragen (index beginnt bei 0, darum + 1)
        if ( gruppe % 2 == 0): # Falls Gruppe 2,4,6,8, ...
            test = test and not (fragen_index == gruppe - 1) # Gruppe 2,4,6,8 soll nicht Gruppe 1,3,5 fragen
        else: # (index % 2 !=0 ) Falls Gruppe 1,3,5,7, .. 
            test = test and not (fragen_index == gruppe + 1) # Gruppe 1,3,5,7 soll nicht Gruppe 2,4,6 fragen
        tests.append(test)
    print(tests)
    return all(tests)
        
def bestimme_frage_gruppe(anzahl_gruppen):
    fertig = False
    while not fertig:
        gruppen = np.arange(0,anzahl_gruppen) +1
        print("originale Reihenfolge:", gruppen)
        # mixe Reihenfolge
        np.random.shuffle(gruppen)
        print("neue Reihenfolge:", gruppen)
        fertig = reihenfolge_erfuellt_kriterien(gruppen)
    print("finale Reihenfolge: Gruppe")
    print(np.arange(0,anzahl_gruppen) + 1, " fragt Gruppe")
    print(gruppen)
    return gruppen

In [16]:
fragen = bestimme_frage_gruppe(14)

originale Reihenfolge: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
neue Reihenfolge: [ 1 11 13  6 12 14  9  8  4  2  3  5  7 10]
1 1
2 11
3 13
4 6
5 12
6 14
7 9
8 8
9 4
10 2
11 3
12 5
13 7
14 10
[False, True, True, True, True, True, True, False, True, True, True, True, True, True]
originale Reihenfolge: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
neue Reihenfolge: [ 5  7  4  1  9  3 10 14  8 12  6 13 11  2]
1 5
2 7
3 4
4 1
5 9
6 3
7 10
8 14
9 8
10 12
11 6
12 13
13 11
14 2
[True, True, False, True, True, True, True, True, True, True, True, True, True, True]
originale Reihenfolge: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
neue Reihenfolge: [ 7  3  9 12 13 10  2  4 11  8  6 14  5  1]
1 7
2 3
3 9
4 12
5 13
6 10
7 2
8 4
9 11
10 8
11 6
12 14
13 5
14 1
[True, True, True, True, True, True, True, True, True, True, True, True, True, True]
finale Reihenfolge: Gruppe
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]  fragt Gruppe
[ 7  3  9 12 13 10  2  4 11  8  6 14  5  1]
