In [3]:
import numpy as np

In [4]:
np.random.randint(0,101,3)

array([66, 48, 20])

In [5]:
def wuerfel(anzahl_gruppen):
    ready = False
    while not ready:
        trial = np.random.randint(0,101,anzahl_gruppen)
        print(trial)
        if len(set(trial)) == len(trial):
            ready = True
    print("Finales Ergebnis:", trial)

In [6]:
wuerfel(2)

[25 40]
Finales Ergebnis: [25 40]


In [7]:
arr=np.array([5,10,11,1,8,4,14])
np.random.shuffle(arr)
print(arr)

[14 10 11  8  4  5  1]


In [8]:
print(np.arange(7)+1+(13-6))
print(arr)

[ 8  9 10 11 12 13 14]
[14 10 11  8  4  5  1]


In [9]:
def reihenfolge_erfuellt_kriterien(reihenfolge):
    tests = []
    for index, fragen_index in enumerate(reihenfolge):
        test = True
        gruppe = index + 1
        print(gruppe, fragen_index)
        test = test and not (gruppe == fragen_index) # Gruppe soll sich nicht selbst fragen (index beginnt bei 0, darum + 1)
        if ( gruppe % 2 == 0): # Falls Gruppe 2,4,6,8, ...
            test = test and not (fragen_index == gruppe - 1) # Gruppe 2,4,6,8 soll nicht Gruppe 1,3,5 fragen
        else: # (index % 2 !=0 ) Falls Gruppe 1,3,5,7, .. 
            test = test and not (fragen_index == gruppe + 1) # Gruppe 1,3,5,7 soll nicht Gruppe 2,4,6 fragen
        tests.append(test)
    print(tests)
    return all(tests)
        
def bestimme_frage_gruppe(anzahl_gruppen):
    fertig = False
    while not fertig:
        gruppen = np.arange(0,anzahl_gruppen) +1
        print("originale Reihenfolge:", gruppen)
        # mixe Reihenfolge
        np.random.shuffle(gruppen)
        print("neue Reihenfolge:", gruppen)
        fertig = reihenfolge_erfuellt_kriterien(gruppen)
    print("finale Reihenfolge: Gruppe")
    print(np.arange(0,anzahl_gruppen) + 1, " fragt Gruppe")
    print(gruppen)
    return gruppen

In [10]:
fragen = bestimme_frage_gruppe(14)

originale Reihenfolge: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
neue Reihenfolge: [ 1  9  3  8 10 12 13  5 14  6  7  4 11  2]
1 1
2 9
3 3
4 8
5 10
6 12
7 13
8 5
9 14
10 6
11 7
12 4
13 11
14 2
[False, True, False, True, True, True, True, True, True, True, True, True, True, True]
originale Reihenfolge: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
neue Reihenfolge: [ 1 11 12  2  8  3 10  6  4  7  9 14 13  5]
1 1
2 11
3 12
4 2
5 8
6 3
7 10
8 6
9 4
10 7
11 9
12 14
13 13
14 5
[False, True, True, True, True, True, True, True, True, True, True, True, False, True]
originale Reihenfolge: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
neue Reihenfolge: [13  7  9  4 11  3  6 10 14  2  8  1 12  5]
1 13
2 7
3 9
4 4
5 11
6 3
7 6
8 10
9 14
10 2
11 8
12 1
13 12
14 5
[True, True, True, False, True, True, True, True, True, True, True, True, True, True]
originale Reihenfolge: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
neue Reihenfolge: [ 4 13 10  2  9 14  1 12  3  5 11  8  6  7]
1 4
2 13
3 10
4 2
5 9
6 14